using DataAccess.Data;
using Database_Video.Entities;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text.RegularExpressions; // Cần thêm cái này để dùng Regex
using System.Threading.Tasks;
using WebVideo.Utility;
using Xabe.FFmpeg;

public class AdvancedDataSeeder
{
    private readonly DataContext _context;
    private readonly UserManager<AppUser> _userManager;
    private readonly RoleManager<AppRole> _roleManager;
    private readonly IWebHostEnvironment _env;
    private readonly HttpClient _httpClient;

    private const string ROOT_PATH = @"D:\ALLVIDEOS";
    private const string FFMPEG_PATH = @"C:\FFmpeg\ffmpeg\bin";

    public AdvancedDataSeeder(DataContext context, UserManager<AppUser> userManager, RoleManager<AppRole> roleManager, IWebHostEnvironment env)
    {
        _context = context;
        _userManager = userManager;
        _roleManager = roleManager;
        _env = env;
        FFmpeg.SetExecutablesPath(FFMPEG_PATH);
        _httpClient = new HttpClient { Timeout = TimeSpan.FromMinutes(30) };
    }

    public async Task SeedAllAsync()
    {
        Console.WriteLine("=== BẮT ĐẦU SEED DATA (PHIÊN BẢN ĐÃ FIX) ===");

        // 1. Tạo Roles
        await SeedRolesAsync();

        // 2. Tạo 200 Users & Channels
        Console.WriteLine("-> Đang tạo 200 Users và Channels...");
        var users = await SeedUsersAsync(200);

        // 3. Seed Videos (Đã sửa tên Clean)
        Console.WriteLine("-> Đang xử lý Video (Clean tên + Thumbnail)...");
        var allVideos = await SeedVideosAsync(users);

        // 4. Tạo dữ liệu tương tác (View, Like, Sub chéo an toàn)
        Console.WriteLine("-> Đang tạo tương tác ảo (View 1k-100k, Like < View, Sub chéo)...");
        await SimulateUserBehaviorsAsync(allVideos);

        Console.WriteLine("=== HOÀN TẤT SEED DATA ===");
    }

    private async Task SeedRolesAsync()
    {
        var roles = new List<string> { SD.AdminRole, SD.UserRole, SD.ModeratorRole };
        foreach (var roleName in roles)
        {
            if (!await _roleManager.RoleExistsAsync(roleName))
            {
                await _roleManager.CreateAsync(new AppRole { Name = roleName });
            }
        }
    }

    private async Task<List<AppUser>> SeedUsersAsync(int count)
    {
        if (await _userManager.Users.CountAsync() >= count)
        {
            Console.WriteLine("   User đã đủ, load lại từ DB.");
            return await _context.Users.Include(u => u.Channel).ToListAsync();
        }

        // Tạo Admin
        if (await _userManager.FindByNameAsync("admin") == null)
        {
            var admin = new AppUser { UserName = "admin", Email = "admin@gmail.com", FullName = "Super Admin", Avatar = "/avatarUser/avt-default.jpg", JoinDate = DateTime.UtcNow };
            var res = await _userManager.CreateAsync(admin, "123456");
            if (res.Succeeded)
            {
                // Cấp toàn bộ quyền cho Admin
                await _userManager.AddToRoleAsync(admin, SD.AdminRole);
                await _userManager.AddToRoleAsync(admin, SD.ModeratorRole);
                await _userManager.AddToRoleAsync(admin, SD.UserRole);
                _context.Channels.Add(new Channel { AppUserId = admin.Id, ChannelName = "Admin Channel", CreatedDate = DateTime.UtcNow });
            }
        }

        // Tạo User thường
        for (int i = 1; i <= count; i++)
        {
            string userName = $"user{i}";
            if (await _userManager.FindByNameAsync(userName) == null)
            {
                var user = new AppUser
                {
                    UserName = userName,
                    Email = $"{userName}@example.com",
                    FullName = $"User {i}",
                    Avatar = "/avatarUser/avt-default.jpg",
                    JoinDate = DateTime.UtcNow.AddDays(-new Random().Next(1, 365))
                };
                var result = await _userManager.CreateAsync(user, "123456");
                if (result.Succeeded)
                {
                    await _userManager.AddToRoleAsync(user, SD.UserRole);
                    var channel = new Channel
                    {
                        AppUserId = user.Id,
                        ChannelName = user.UserName + " Channel",
                        CreatedDate = DateTime.UtcNow,
                        About = "This is a demo channel generated by seeder."
                    };
                    _context.Channels.Add(channel);
                }
            }
            if (i % 50 == 0) Console.Write(".");
        }
        Console.WriteLine();
        await _context.SaveChangesAsync();

        // Quan trọng: Load lại dữ liệu tươi từ DB để đảm bảo ID khớp 100%
        return await _context.Users.Include(u => u.Channel).ToListAsync();
    }

    private async Task<List<Video>> SeedVideosAsync(List<AppUser> users)
    {
        var allVideos = new List<Video>();
        var random = new Random();

        string nonCelebPath = Path.Combine(ROOT_PATH, "NonCeleb_Video");
        if (!Directory.Exists(nonCelebPath)) return await _context.Videos.ToListAsync();

        foreach (var catDir in Directory.GetDirectories(nonCelebPath))
        {
            string categoryName = new DirectoryInfo(catDir).Name;
            var category = await GetOrCreateCategory(categoryName);

            var files = Directory.GetFiles(catDir, "*.mp4");
            foreach (var file in files)
            {
                string fileNameToCheck = Path.GetFileName(file);
                // Sửa lỗi CS1061: Dùng Set<VideoFile>() thay vì .VideoFiles
                if (_context.Set<VideoFile>().Any(vf => vf.FilePath.Contains(fileNameToCheck))) continue;

                var owner = users[random.Next(users.Count)];
                var channelId = owner.Channel?.Id ?? (await _context.Channels.FirstAsync()).Id;

                // === XỬ LÝ TÊN VIDEO (Clean Title) ===
                string rawName = Path.GetFileNameWithoutExtension(file);

                // 1. Xóa các từ khóa rác (không phân biệt hoa thường)
                string tempName = rawName;
                tempName = Regex.Replace(tempName, "mixkit", "", RegexOptions.IgnoreCase);
                tempName = Regex.Replace(tempName, "hd-ready", "", RegexOptions.IgnoreCase); // Có gạch ngang
                tempName = Regex.Replace(tempName, "hd ready", "", RegexOptions.IgnoreCase); // Không gạch ngang

                // 2. Thay thế ký tự đặc biệt bằng khoảng trắng
                tempName = tempName.Replace("-", " ").Replace("_", " ");

                // 3. Xóa các con số (ID) thường xuất hiện trong tên file (ví dụ: 23246)
                // Regex này tìm các chuỗi số và thay bằng rỗng
                tempName = Regex.Replace(tempName, @"\d+", "");

                // 4. Cắt khoảng trắng thừa và viết hoa chữ cái đầu
                string cleanTitle = tempName.Trim();
                // Xóa nhiều khoảng trắng liên tiếp thành 1
                cleanTitle = Regex.Replace(cleanTitle, @"\s+", " ");

                if (cleanTitle.Length > 0)
                    cleanTitle = char.ToUpper(cleanTitle[0]) + cleanTitle.Substring(1);
                else
                    cleanTitle = "Untitled Video";
                // =====================================

                var (thumbnailPath, duration) = await ProcessVideoFileWithFFmpeg(file);

                var video = new Video
                {
                    Id = Guid.NewGuid(),
                    Title = cleanTitle,
                    Description = $"Video demo about {cleanTitle} in {categoryName}.",
                    CategoryId = category.Id,
                    ChannelId = channelId,
                    UploadDate = DateTime.UtcNow.AddDays(-random.Next(0, 60)),
                    Thumbnail = thumbnailPath,
                    Duration = duration,
                    Views = 0,
                    RecognizedCelebrities = "Không yêu cầu nhận diện",
                    CelebrityFrames = "{}",
                    VideoFile = new VideoFile
                    {
                        Id = Guid.NewGuid(),
                        FilePath = file,
                        ContentType = "video/mp4",
                        Extension = ".mp4"
                    }
                };

                _context.Videos.Add(video);
                allVideos.Add(video);
                Console.Write(".");
            }
        }
        Console.WriteLine();
        await _context.SaveChangesAsync();
        return await _context.Videos.ToListAsync();
    }

    private async Task SimulateUserBehaviorsAsync(List<Video> videos)
    {
        // Load lại danh sách User và Channel mới nhất từ DB để tránh lỗi Khóa Ngoại
        var dbUsers = await _context.Users.Include(u => u.Channel).ToListAsync();
        var dbChannels = await _context.Channels.ToListAsync();

        if (videos.Count == 0 || dbUsers.Count == 0) return;

        var random = new Random();

        // --- PHẦN 1: TẠO VIEWS VÀ LIKES (HOT & FLOP) ---
        Console.WriteLine("   + Đang tạo Views (1k-100k) và Likes (<Views)...");
        int videoCount = 0;

        foreach (var video in videos)
        {
            // Random view từ 1.000 đến 100.000
            int targetViews = random.Next(1000, 100001);

            // Cập nhật số hiển thị
            video.Views = targetViews;
            _context.Videos.Update(video);

            // Tạo khoảng 20-40 người xem "đại diện" trong bảng VideoView
            int numberOfViewers = random.Next(20, 40);
            int viewsPerUserBase = targetViews / numberOfViewers;

            for (int i = 0; i < numberOfViewers; i++)
            {
                var randomUser = dbUsers[random.Next(dbUsers.Count)];

                // Check trùng bằng Any() ở đây chấp nhận được vì số lượng ít
                if (!_context.VideoViews.Any(vv => vv.AppUserId == randomUser.Id && vv.VideoId == video.Id))
                {
                    int specificVisitCount = viewsPerUserBase + random.Next(-viewsPerUserBase / 2, viewsPerUserBase / 2);
                    if (specificVisitCount <= 0) specificVisitCount = 1;

                    var view = new VideoView
                    {
                        AppUserId = randomUser.Id,
                        VideoId = video.Id,
                        NumberOfVisit = specificVisitCount,
                        LastVisit = DateTime.UtcNow.AddDays(-random.Next(0, 30)),
                        ProgressSeconds = random.Next(60, 600),
                        IpAddress = "127.0.0.1"
                    };
                    _context.VideoViews.Add(view);
                }
            }

            // 2. Random Likes: 1% đến 15% của Views (Biến động mạnh hơn)
            double likePercentage = random.NextDouble() * (0.15 - 0.01) + 0.01; // 0.01 to 0.15
            int targetLikes = (int)(targetViews * likePercentage);

            // Giới hạn like không vượt quá số user trong DB
            int maxPossibleLikes = Math.Min(targetLikes, dbUsers.Count);

            // Lấy danh sách user ngẫu nhiên để like
            var potentialLikers = dbUsers.OrderBy(x => Guid.NewGuid()).Take(maxPossibleLikes).ToList();

            foreach (var liker in potentialLikers)
            {
                if (!_context.LikeDislikes.Any(l => l.AppUserId == liker.Id && l.VideoId == video.Id))
                {
                    _context.LikeDislikes.Add(new LikeDislike(video.Id, liker.Id, true));
                }
            }

            videoCount++;
            if (videoCount % 20 == 0)
            {
                Console.Write(".");
                await _context.SaveChangesAsync(); // Lưu từng đợt để tránh tràn bộ nhớ
            }
        }
        await _context.SaveChangesAsync(); // Lưu phần còn lại
        Console.WriteLine("\n   + Đã xong phần Video/Like.");


        // --- PHẦN 2: SUB CHÉO (ĐÃ FIX LỖI KHÓA NGOẠI & HIỆU SUẤT) ---
        Console.WriteLine("   + Đang tạo Sub chéo (Sử dụng HashSet để tối ưu)...");

        // Lấy danh sách sub hiện có vào RAM để check nhanh (tránh gọi DB liên tục)
        // Key: "UserId_ChannelId"
        var existingSubs = await _context.Subscribes
            .Select(s => s.AppUserId + "_" + s.ChannelId)
            .ToListAsync();
        var subSet = new HashSet<string>(existingSubs);

        var newSubs = new List<Subscribe>();
        int subBatchCount = 0;

        foreach (var user in dbUsers)
        {
            // Mỗi user sub ngẫu nhiên 5 - 30 kênh
            int subsToMake = random.Next(5, 30);

            // Lấy danh sách kênh ngẫu nhiên (trừ kênh của mình)
            var targetChannels = dbChannels
                .Where(c => c.AppUserId != user.Id)
                .OrderBy(x => Guid.NewGuid())
                .Take(subsToMake)
                .ToList();

            foreach (var channel in targetChannels)
            {
                string key = user.Id + "_" + channel.Id;

                // Kiểm tra trong HashSet (cực nhanh, không lỗi connection)
                if (!subSet.Contains(key))
                {
                    newSubs.Add(new Subscribe(user.Id, channel.Id));
                    subSet.Add(key); // Đánh dấu đã thêm
                }
            }

            // Lưu theo lô 50 user một lần
            subBatchCount++;
            if (subBatchCount % 50 == 0 && newSubs.Any())
            {
                await _context.Subscribes.AddRangeAsync(newSubs);
                await _context.SaveChangesAsync();
                newSubs.Clear(); // Xóa danh sách tạm sau khi lưu
                Console.Write("+");
            }
        }

        // Lưu số còn sót lại
        if (newSubs.Any())
        {
            await _context.Subscribes.AddRangeAsync(newSubs);
            await _context.SaveChangesAsync();
        }

        Console.WriteLine("\n-> Đã cập nhật xong toàn bộ dữ liệu Subscribe.");
    }

    private async Task<Category> GetOrCreateCategory(string name)
    {
        var cat = await _context.Categories.FirstOrDefaultAsync(c => c.CategoryName == name);
        if (cat == null)
        {
            cat = new Category { CategoryName = name, CreatedDate = DateTime.UtcNow };
            _context.Categories.Add(cat);
            await _context.SaveChangesAsync();
        }
        return cat;
    }

    private async Task<(string thumbnailWebPath, string duration)> ProcessVideoFileWithFFmpeg(string videoPath)
    {
        try
        {
            IMediaInfo mediaInfo = await FFmpeg.GetMediaInfo(videoPath);
            string duration = mediaInfo.Duration.ToString(@"mm\:ss");

            string thumbFileName = $"{Guid.NewGuid()}.jpg";
            string thumbFolder = Path.Combine(_env.WebRootPath, "images", "thumbnails");
            if (!Directory.Exists(thumbFolder)) Directory.CreateDirectory(thumbFolder);

            string outputThumbPath = Path.Combine(thumbFolder, thumbFileName);

            IConversion conversion = await FFmpeg.Conversions.FromSnippet.Snapshot(
                videoPath, outputThumbPath, TimeSpan.FromSeconds(2)
            );
            await conversion.Start();

            return ($"/images/thumbnails/{thumbFileName}", duration);
        }
        catch
        {
            return ("/avatarUser/avt-default.jpg", "00:00");
        }
    }
}